version: "3.8"

services:
  
  skin-sight-frontend:
    build:
      context: .
      target: development
    volumes:
      - type: bind
        source: ./
        target: /app
      - /app/node_modules

    command: npm start
    ports:
      - "3000:3000"